### ISSUE TITLE
Webpage display bugs

### ISSUE THREAD

**Issue by lizji1992** [smithlabcode/MethBase#16]
The bugs of showing wrong %CpG and float #HMR/#PMR/#DMR are fixed. The description webpages needed to be rebuilt. However I don't have the permission to do that - so could everyone do the <code>set-up-project</code> again? DON'T NEED to call <code>update-trackhub</code>.  Or can I get the root access @andrewdavidsmith ? Then I don't need to bother others.

**Comment by lizji1992** [comment]
Fixed. Thank everybody.

**Comment by mengzhou** [comment]
I have a question about the permission. I think those data files on smithlab server have been set to writable to the group (chmod 664), and the group is labdata, right? If the case is some permissions are not correctly set, can you add chmod command in the setup script?

**Comment by lizji1992** [comment]
Good idea. I will add this to the script.

**Comment by andrewdavidsmith** [comment]
It feels to me like this might be the wrong approach.

The script is supposed to read from one place, and write something totally different.

Having a side-effect of modifying permissions that might be very heterogeneous (the assumption behind the need for such modification) could be difficult to implement and lead to problems.

Why not just make sure everyone properly sets their permissions?

If the script cannot read what it needs, then it should report such in a log of errors, and skip the files.
