### ISSUE TITLE
Incomplete ESC cell type track set?

### ISSUE THREAD

**Issue by andrewdavidsmith** [smithlabcode/MethBase#20]
Should the HUES methylome be included in the ESC cell type track set?

**Comment by bdecato** [comment]
Absolutely.  It looks like it was just missed when we originally set up the tracks, rather than being an omission from inclusion after incorporation of project.config style files.  @lizji1992 should I make a project.config file for the Lister-Brain-2013 project?

**Comment by lizji1992** [comment]
Seems a lot of work to do. In fact I can use Qiang's codes to update the track then we don't need to write project.config.

**Comment by bdecato** [comment]
@lizji1992 You added this, right?

**Comment by lizji1992** [comment]
HUES was wrongly included in Brain track before.. Now fix it.

**Comment by andrewdavidsmith** [comment]
Hi Liz.

We absolutely need to go over your slides before you present to the group. It's important that you present  well tomorrow.
